controller_list:
  - name: fake_rat_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - base_joint
      - elbow_joint
      - wrist_joint
initial:  # Define initial robot poses per group
  - group: rat_arm
    pose: home